# Generated by Django 4.0.7 on 2022-09-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0002_user_is_owner_owner_driver_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="experience_in_years",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="salary",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="stocks_owned",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
