# Generated by Django 4.0.7 on 2022-09-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "Managementapp",
            "0003_alter_driver_experience_in_years_alter_driver_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Company_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=20, null=True)),
                ("lastname", models.CharField(max_length=20, null=True)),
                ("email", models.CharField(max_length=20, null=True)),
                (
                    "emp_record_id",
                    models.CharField(max_length=20, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truck_id", models.CharField(max_length=50, null=True, unique=True)),
                ("model_name", models.CharField(max_length=50, null=True)),
                ("miles_per_gallon", models.CharField(max_length=50, null=True)),
                ("drive_type", models.CharField(max_length=50, null=True)),
                ("engine_type", models.CharField(max_length=50, null=True)),
                ("color", models.CharField(max_length=20, null=True)),
                ("horsepower", models.CharField(max_length=50, null=True)),
                ("fuel_capacity", models.CharField(max_length=50, null=True)),
                ("no_plate", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssignTruck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Managementapp.company_detail",
                    ),
                ),
                (
                    "truck",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Managementapp.truck",
                    ),
                ),
            ],
        ),
    ]
