# Generated by Django 4.0.7 on 2022-09-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0004_company_detail_truck_assigntruck"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company_detail",
            name="emp_record_id",
        ),
    ]
