# Generated by Django 4.0.7 on 2022-09-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0007_remove_truck_truck_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="email",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="assigntruck",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Managementapp.driver"
            ),
        ),
        migrations.DeleteModel(
            name="Company_detail",
        ),
    ]
