# Generated by Django 4.0.7 on 2022-09-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0008_driver_email_alter_assigntruck_driver_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, null=True)),
                ("lastname", models.CharField(max_length=20, null=True)),
                ("email", models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
