# Generated by Django 4.0.7 on 2022-09-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0009_company_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_detail",
            name="rental_code",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="rental_code",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Managementapp.company_detail",
            ),
        ),
        migrations.AlterField(
            model_name="assigntruck",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Managementapp.company_detail",
            ),
        ),
    ]
