# Generated by Django 4.0.7 on 2022-09-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0011_remove_driver_rental_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="rental_code",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Managementapp.company_detail",
            ),
        ),
    ]
