# Generated by Django 4.0.7 on 2022-09-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0012_driver_rental_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="rental_code",
        ),
        migrations.AlterField(
            model_name="assigntruck",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Managementapp.driver"
            ),
        ),
        migrations.DeleteModel(
            name="Company_detail",
        ),
    ]
