# Generated by Django 4.0.7 on 2022-09-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Managementapp",
            "0013_remove_driver_rental_code_alter_assigntruck_driver_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="name",
            new_name="firstname",
        ),
        migrations.AddField(
            model_name="driver",
            name="lastname",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
