# Generated by Django 4.0.7 on 2022-09-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0014_rename_name_driver_firstname_driver_lastname"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="username",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
