# Generated by Django 4.0.7 on 2022-09-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0017_driver_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
