# Generated by Django 4.0.7 on 2022-09-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0020_remove_driver_user_alter_driver_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="username",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="name",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="experience_in_years",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="salary",
        ),
    ]
