# Generated by Django 4.0.7 on 2022-09-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0023_driver_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigntruck",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Managementapp.driver",
                unique=True,
            ),
        ),
    ]
