# Generated by Django 4.0.7 on 2022-09-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Managementapp", "0026_rename_driver_assigntruck_driver_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assigntruck",
            old_name="driver_id",
            new_name="driver",
        ),
        migrations.RenameField(
            model_name="assigntruck",
            old_name="vehicle_id",
            new_name="vehicle",
        ),
    ]
